import type { ComponentType } from "../component-types";

export type RuntimeWidget = ComponentType & {
  childIndex?: number;
  __dynamicCreated?: boolean;
};

/**
 * Creates a clientscript-created widget using the client Widget constructor
 * defaults rather than inheriting data from its parent.
 *
 * CC_CREATE in the client allocates a fresh Widget, then only assigns type,
 * parent/id, child index and IF3 state. Keeping these defaults centralized
 * prevents renderer behavior from depending on whichever parent happened to
 * create the child.
 */
export function createDynamicWidget(
  parentPackedId: number,
  type: number,
  childIndex: number,
): RuntimeWidget {
  return {
    v3: true,
    type,
    buttonType: 0,
    clientCode: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    tempWidth: 0,
    tempHeight: 0,
    trans1: 0,
    layer: parentPackedId,
    mouseOverRedirect: -1,
    cs1Comparisons: null,
    cs1ComparisonValues: null,
    cs1Instructions: null,
    scrollHeight: 0,
    hide: false,
    fill: false,
    textAlignH: 0,
    textAlignV: 0,
    textLineHeight: 0,
    textFont: -1,
    textShadow: false,
    secondaryText: "",
    colour1: 0,
    colour2: 0,
    mouseOverColour1: 0,
    mouseOverColour2: 0,
    graphic: -1,
    secondaryGraphic: -1,
    modelKind: 1,
    model: -1,
    secondaryModelKind: 1,
    secondaryModel: -1,
    modelAnim: -1,
    secondaryModelAnim: -1,
    modelZoom: 100,
    modelAngleX: 0,
    modelAngleY: 0,
    text: "",
    targetVerb: "",
    targetBase: "",
    events: 0,
    buttonText: "Ok",
    widthMode: 0,
    heightMode: 0,
    xMode: 0,
    yMode: 0,
    scrollWidth: 0,
    noClickThrough: false,
    angle2d: 0,
    tiling: false,
    outline: 0,
    graphicShadow: 0,
    vFlip: false,
    hFlip: false,
    modelX: 0,
    modelY: 0,
    modelAngleZ: 0,
    modelOrthog: false,
    modelObjWidth: 0,
    lineWid: 1,
    lineDirection: false,
    opBase: "",
    op: [],
    dragDeadZone: 0,
    dragDeadTime: 0,
    draggableBehavior: false,
    onLoad: null,
    onMouseOver: null,
    onMouseLeave: null,
    onTargetLeave: null,
    onTargetEnter: null,
    onVarTransmit: null,
    onInvTransmit: null,
    onStatTransmit: null,
    onTimer: null,
    onOp: null,
    onMouseRepeat: null,
    onClick: null,
    onClickRepeat: null,
    onRelease: null,
    onHold: null,
    onDrag: null,
    onDragComplete: null,
    onScrollWheel: null,
    onVarTransmitList: null,
    onInvTransmitList: null,
    onStatTransmitList: null,
    packedId: parentPackedId,
    internalName: null,
    id: parentPackedId,
    children: null,
    childIndex,
    __dynamicCreated: true,
  };
}
